### ISSUE TITLE
Allow conversion to hexadecimal format

### ISSUE THREAD

**Issue by hugolpz** [d3/d3-color#40] opened 2018-03-20 21:26 UTC
I may have missed it, but It seems there is no native way to convert from rgb or others to hexadecimal.
This can however be quite handy. See : https://jsfiddle.net/Mottie/xcqpF/1/light/

**Comment by mbostock** [comment] 2018-03-20 21:42
Duplicate of #38.

**Closed by mbostock** 2018-03-20 21:42 UTC
